# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskmanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(392, 288)
        Main.setSizeGripEnabled(False)
        self.layoutWidget = QtWidgets.QWidget(Main)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 266))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 4, 1, 1, 1)
        self.label_Lists = QtWidgets.QLabel(self.layoutWidget)
        self.label_Lists.setObjectName("label_Lists")
        self.gridLayout.addWidget(self.label_Lists, 0, 0, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 4, 2, 1, 1)
        self.pushButton_refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.gridLayout.addWidget(self.pushButton_refresh, 4, 3, 1, 1)
        self.comboBox_lists = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_lists.setObjectName("comboBox_lists")
        self.gridLayout.addWidget(self.comboBox_lists, 0, 2, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 4)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Dialog"))
        self.pushButton.setText(_translate("Main", "Done"))
        self.pushButton_add.setText(_translate("Main", "Add"))
        self.label_Lists.setText(_translate("Main", "Lists :"))
        self.pushButton_delete.setText(_translate("Main", "Delete"))
        self.pushButton_refresh.setText(_translate("Main", "Refresh"))
